/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard.index";
import { Route as DashboardTransportRouteImport } from "./routes/dashboard/transport";
import { Route as DashboardTimetableRouteImport } from "./routes/dashboard/timetable";
import { Route as DashboardTeachersRouteImport } from "./routes/dashboard/teachers";
import { Route as DashboardStudentsRouteImport } from "./routes/dashboard/students";
import { Route as DashboardLibraryRouteImport } from "./routes/dashboard/library";
import { Route as DashboardLearningRouteImport } from "./routes/dashboard/learning";
import { Route as DashboardGradesRouteImport } from "./routes/dashboard/grades";
import { Route as DashboardFinanceRouteImport } from "./routes/dashboard/finance";
import { Route as DashboardFeesRouteImport } from "./routes/dashboard/fees";
import { Route as DashboardExamsRouteImport } from "./routes/dashboard/exams";
import { Route as DashboardClassesRouteImport } from "./routes/dashboard/classes";
import { Route as DashboardChildrenRouteImport } from "./routes/dashboard/children";
import { Route as DashboardAttendanceRouteImport } from "./routes/dashboard/attendance";
import { Route as DashboardAssignmentsRouteImport } from "./routes/dashboard/assignments";
import { Route as DashboardAnnouncementsRouteImport } from "./routes/dashboard/announcements";
import { Route as DashboardAiTutorRouteImport } from "./routes/dashboard/ai-tutor";

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardTransportRoute = DashboardTransportRouteImport.update({
  id: "/transport",
  path: "/transport",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardTimetableRoute = DashboardTimetableRouteImport.update({
  id: "/timetable",
  path: "/timetable",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardTeachersRoute = DashboardTeachersRouteImport.update({
  id: "/teachers",
  path: "/teachers",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: "/students",
  path: "/students",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: "/library",
  path: "/library",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardLearningRoute = DashboardLearningRouteImport.update({
  id: "/learning",
  path: "/learning",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardGradesRoute = DashboardGradesRouteImport.update({
  id: "/grades",
  path: "/grades",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: "/finance",
  path: "/finance",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: "/fees",
  path: "/fees",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardExamsRoute = DashboardExamsRouteImport.update({
  id: "/exams",
  path: "/exams",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: "/classes",
  path: "/classes",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardChildrenRoute = DashboardChildrenRouteImport.update({
  id: "/children",
  path: "/children",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: "/attendance",
  path: "/attendance",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: "/assignments",
  path: "/assignments",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: "/announcements",
  path: "/announcements",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAiTutorRoute = DashboardAiTutorRouteImport.update({
  id: "/ai-tutor",
  path: "/ai-tutor",
  getParentRoute: () => DashboardRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/dashboard/ai-tutor": typeof DashboardAiTutorRoute;
  "/dashboard/announcements": typeof DashboardAnnouncementsRoute;
  "/dashboard/assignments": typeof DashboardAssignmentsRoute;
  "/dashboard/attendance": typeof DashboardAttendanceRoute;
  "/dashboard/children": typeof DashboardChildrenRoute;
  "/dashboard/classes": typeof DashboardClassesRoute;
  "/dashboard/exams": typeof DashboardExamsRoute;
  "/dashboard/fees": typeof DashboardFeesRoute;
  "/dashboard/finance": typeof DashboardFinanceRoute;
  "/dashboard/grades": typeof DashboardGradesRoute;
  "/dashboard/learning": typeof DashboardLearningRoute;
  "/dashboard/library": typeof DashboardLibraryRoute;
  "/dashboard/students": typeof DashboardStudentsRoute;
  "/dashboard/teachers": typeof DashboardTeachersRoute;
  "/dashboard/timetable": typeof DashboardTimetableRoute;
  "/dashboard/transport": typeof DashboardTransportRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/dashboard/ai-tutor": typeof DashboardAiTutorRoute;
  "/dashboard/announcements": typeof DashboardAnnouncementsRoute;
  "/dashboard/assignments": typeof DashboardAssignmentsRoute;
  "/dashboard/attendance": typeof DashboardAttendanceRoute;
  "/dashboard/children": typeof DashboardChildrenRoute;
  "/dashboard/classes": typeof DashboardClassesRoute;
  "/dashboard/exams": typeof DashboardExamsRoute;
  "/dashboard/fees": typeof DashboardFeesRoute;
  "/dashboard/finance": typeof DashboardFinanceRoute;
  "/dashboard/grades": typeof DashboardGradesRoute;
  "/dashboard/learning": typeof DashboardLearningRoute;
  "/dashboard/library": typeof DashboardLibraryRoute;
  "/dashboard/students": typeof DashboardStudentsRoute;
  "/dashboard/teachers": typeof DashboardTeachersRoute;
  "/dashboard/timetable": typeof DashboardTimetableRoute;
  "/dashboard/transport": typeof DashboardTransportRoute;
  "/dashboard": typeof DashboardIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/dashboard/ai-tutor": typeof DashboardAiTutorRoute;
  "/dashboard/announcements": typeof DashboardAnnouncementsRoute;
  "/dashboard/assignments": typeof DashboardAssignmentsRoute;
  "/dashboard/attendance": typeof DashboardAttendanceRoute;
  "/dashboard/children": typeof DashboardChildrenRoute;
  "/dashboard/classes": typeof DashboardClassesRoute;
  "/dashboard/exams": typeof DashboardExamsRoute;
  "/dashboard/fees": typeof DashboardFeesRoute;
  "/dashboard/finance": typeof DashboardFinanceRoute;
  "/dashboard/grades": typeof DashboardGradesRoute;
  "/dashboard/learning": typeof DashboardLearningRoute;
  "/dashboard/library": typeof DashboardLibraryRoute;
  "/dashboard/students": typeof DashboardStudentsRoute;
  "/dashboard/teachers": typeof DashboardTeachersRoute;
  "/dashboard/timetable": typeof DashboardTimetableRoute;
  "/dashboard/transport": typeof DashboardTransportRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/signup"
    | "/dashboard/ai-tutor"
    | "/dashboard/announcements"
    | "/dashboard/assignments"
    | "/dashboard/attendance"
    | "/dashboard/children"
    | "/dashboard/classes"
    | "/dashboard/exams"
    | "/dashboard/fees"
    | "/dashboard/finance"
    | "/dashboard/grades"
    | "/dashboard/learning"
    | "/dashboard/library"
    | "/dashboard/students"
    | "/dashboard/teachers"
    | "/dashboard/timetable"
    | "/dashboard/transport"
    | "/dashboard/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/dashboard/ai-tutor"
    | "/dashboard/announcements"
    | "/dashboard/assignments"
    | "/dashboard/attendance"
    | "/dashboard/children"
    | "/dashboard/classes"
    | "/dashboard/exams"
    | "/dashboard/fees"
    | "/dashboard/finance"
    | "/dashboard/grades"
    | "/dashboard/learning"
    | "/dashboard/library"
    | "/dashboard/students"
    | "/dashboard/teachers"
    | "/dashboard/timetable"
    | "/dashboard/transport"
    | "/dashboard";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/signup"
    | "/dashboard/ai-tutor"
    | "/dashboard/announcements"
    | "/dashboard/assignments"
    | "/dashboard/attendance"
    | "/dashboard/children"
    | "/dashboard/classes"
    | "/dashboard/exams"
    | "/dashboard/fees"
    | "/dashboard/finance"
    | "/dashboard/grades"
    | "/dashboard/learning"
    | "/dashboard/library"
    | "/dashboard/students"
    | "/dashboard/teachers"
    | "/dashboard/timetable"
    | "/dashboard/transport"
    | "/dashboard/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/transport": {
      id: "/dashboard/transport";
      path: "/transport";
      fullPath: "/dashboard/transport";
      preLoaderRoute: typeof DashboardTransportRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/timetable": {
      id: "/dashboard/timetable";
      path: "/timetable";
      fullPath: "/dashboard/timetable";
      preLoaderRoute: typeof DashboardTimetableRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/teachers": {
      id: "/dashboard/teachers";
      path: "/teachers";
      fullPath: "/dashboard/teachers";
      preLoaderRoute: typeof DashboardTeachersRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/students": {
      id: "/dashboard/students";
      path: "/students";
      fullPath: "/dashboard/students";
      preLoaderRoute: typeof DashboardStudentsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/library": {
      id: "/dashboard/library";
      path: "/library";
      fullPath: "/dashboard/library";
      preLoaderRoute: typeof DashboardLibraryRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/learning": {
      id: "/dashboard/learning";
      path: "/learning";
      fullPath: "/dashboard/learning";
      preLoaderRoute: typeof DashboardLearningRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/grades": {
      id: "/dashboard/grades";
      path: "/grades";
      fullPath: "/dashboard/grades";
      preLoaderRoute: typeof DashboardGradesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/finance": {
      id: "/dashboard/finance";
      path: "/finance";
      fullPath: "/dashboard/finance";
      preLoaderRoute: typeof DashboardFinanceRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/fees": {
      id: "/dashboard/fees";
      path: "/fees";
      fullPath: "/dashboard/fees";
      preLoaderRoute: typeof DashboardFeesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/exams": {
      id: "/dashboard/exams";
      path: "/exams";
      fullPath: "/dashboard/exams";
      preLoaderRoute: typeof DashboardExamsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/classes": {
      id: "/dashboard/classes";
      path: "/classes";
      fullPath: "/dashboard/classes";
      preLoaderRoute: typeof DashboardClassesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/children": {
      id: "/dashboard/children";
      path: "/children";
      fullPath: "/dashboard/children";
      preLoaderRoute: typeof DashboardChildrenRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/attendance": {
      id: "/dashboard/attendance";
      path: "/attendance";
      fullPath: "/dashboard/attendance";
      preLoaderRoute: typeof DashboardAttendanceRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/assignments": {
      id: "/dashboard/assignments";
      path: "/assignments";
      fullPath: "/dashboard/assignments";
      preLoaderRoute: typeof DashboardAssignmentsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/announcements": {
      id: "/dashboard/announcements";
      path: "/announcements";
      fullPath: "/dashboard/announcements";
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/ai-tutor": {
      id: "/dashboard/ai-tutor";
      path: "/ai-tutor";
      fullPath: "/dashboard/ai-tutor";
      preLoaderRoute: typeof DashboardAiTutorRouteImport;
      parentRoute: typeof DashboardRoute;
    };
  }
}

interface DashboardRouteChildren {
  DashboardAiTutorRoute: typeof DashboardAiTutorRoute;
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute;
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute;
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute;
  DashboardChildrenRoute: typeof DashboardChildrenRoute;
  DashboardClassesRoute: typeof DashboardClassesRoute;
  DashboardExamsRoute: typeof DashboardExamsRoute;
  DashboardFeesRoute: typeof DashboardFeesRoute;
  DashboardFinanceRoute: typeof DashboardFinanceRoute;
  DashboardGradesRoute: typeof DashboardGradesRoute;
  DashboardLearningRoute: typeof DashboardLearningRoute;
  DashboardLibraryRoute: typeof DashboardLibraryRoute;
  DashboardStudentsRoute: typeof DashboardStudentsRoute;
  DashboardTeachersRoute: typeof DashboardTeachersRoute;
  DashboardTimetableRoute: typeof DashboardTimetableRoute;
  DashboardTransportRoute: typeof DashboardTransportRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiTutorRoute: DashboardAiTutorRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardChildrenRoute: DashboardChildrenRoute,
  DashboardClassesRoute: DashboardClassesRoute,
  DashboardExamsRoute: DashboardExamsRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardGradesRoute: DashboardGradesRoute,
  DashboardLearningRoute: DashboardLearningRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardTeachersRoute: DashboardTeachersRoute,
  DashboardTimetableRoute: DashboardTimetableRoute,
  DashboardTransportRoute: DashboardTransportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
